# Generated by Django 5.2.4 on 2025-07-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='filter_type',
            field=models.CharField(choices=[('dropdown', 'Dropdown'), ('buttons', 'Buttons')], default='dropdown', max_length=50),
        ),
    ]
