# Generated by Django 5.2.4 on 2025-07-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_filter_filter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='allows_automated_delivery',
            field=models.BooleanField(default=False, help_text='Check if listings in this category can be for automated delivery.'),
        ),
    ]
