# Generated by Django 5.2.4 on 2025-07-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_category_commission_rate_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Default site-wide commission rate in % (e.g., 10.00).', max_digits=5)),
            ],
        ),
    ]
