# Generated by Django 5.2.4 on 2025-07-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_gamecategory_allows_automated_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='internal_name',
            field=models.CharField(help_text='e.g., Account Filters, Item Properties. Can be blank for existing filters.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(blank=True, help_text='e.g., Platform, Rank, Region', max_length=100),
        ),
    ]
