# Generated by Django 5.2.4 on 2025-07-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_filter_internal_name_alter_filter_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='filter',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='A number to determine the display order. Lower numbers show first.'),
        ),
    ]