# Generated by Django 5.2.4 on 2025-07-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_gamecategory_primary_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='append_to_title',
            field=models.BooleanField(default=False, help_text="If checked, this filter's value will be appended to the listing title."),
        ),
    ]