# Generated by Django 5.2.4 on 2025-07-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_usergameboost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='post_purchase_message',
            field=models.TextField(blank=True, verbose_name='Message to the buyer after payment'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='In Stock'),
        ),
    ]
