# Generated by Django 5.2.4 on 2025-07-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0011_profile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='profile_pics', default='default.jpg'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('marketplace', 'Profile')
            .objects.filter(image='profile_pics/default.jpg').update(image='default.jpg'),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
