# Generated by Django 5.2.4 on 2025-07-25 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_category_snapshots', to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='order',
            name='description_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='filter_options_snapshot',
            field=models.ManyToManyField(blank=True, related_name='order_filter_options_snapshots', to='marketplace.filteroption'),
        ),
        migrations.AddField(
            model_name='order',
            name='game_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_game_snapshots', to='marketplace.game'),
        ),
        migrations.AddField(
            model_name='order',
            name='listing_title_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]