# Generated by Django 5.2.4 on 2025-07-25 06:46

from django.db import migrations

def backfill_order_snapshots(apps, schema_editor):
    Order = apps.get_model('marketplace', 'Order')
    # Loop through existing orders that still have a product linked
    for order in Order.objects.filter(product__isnull=False).select_related('product__game', 'product__category').prefetch_related('product__filter_options'):
        order.listing_title_snapshot = order.product.listing_title
        order.description_snapshot = order.product.description
        order.game_snapshot = order.product.game
        order.category_snapshot = order.product.category
        order.save() # Save the simple fields first
        order.filter_options_snapshot.set(order.product.filter_options.all()) # Then set the M2M

class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_order_snapshots'),
    ]

    operations = [
        migrations.RunPython(backfill_order_snapshots, migrations.RunPython.noop),
    ]