# Generated by Django 5.2.4 on 2025-07-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0013_backfill_order_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
