# Generated by Django 5.2.4 on 2025-07-29 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_backfill_order_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_disputed',
            field=models.BooleanField(default=False, help_text='Whether this conversation has dispute resolution active'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='moderator',
            field=models.ForeignKey(blank=True, help_text='Admin/moderator who joined for dispute resolution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='Can join conversations for dispute resolution'),
        ),
    ]
