# Generated by Django 5.2.4 on 2025-08-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_alter_message_is_read_alter_message_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique order identifier', max_length=20, null=True, unique=True),
        ),
    ]
