# Generated by Django 5.2.4 on 2025-08-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_update_order_id_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='supportticket',
            name='issue_category',
            field=models.CharField(choices=[('ORDER', 'Issue with an Order'), ('ACCOUNT', 'Account Related Issue'), ('PAYMENT', 'Payment & Billing'), ('TECHNICAL', 'Technical Support'), ('GENERAL', 'General Inquiry'), ('BUG_REPORT', 'Bug Report'), ('FEATURE_REQUEST', 'Feature Request')], default='GENERAL', help_text='What type of issue are you experiencing?', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='order_number',
            field=models.CharField(blank=True, help_text='If this is about a specific order, please provide the order number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user_type',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller')], default='BUYER', help_text='Are you contacting us as a buyer or seller?', max_length=10),
        ),
    ]
