# Generated by Django 5.2.4 on 2025-08-01 11:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_add_support_ticket_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid_from_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid from user balance', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid_via_payment_method',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid via external payment method', max_digits=10),
        ),
    ]
