# Generated by Django 5.2.4 on 2025-08-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_order_amount_paid_from_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='offline_broadcast_at',
            field=models.DateTimeField(blank=True, help_text='Last time offline status was broadcasted', null=True),
        ),
    ]
