# Generated by Django 5.2.4 on 2025-08-02 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_blockeduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified_seller',
            field=models.BooleanField(default=False, help_text='Verified sellers can withdraw funds immediately'),
        ),
        migrations.CreateModel(
            name='HeldFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('release_at', models.DateTimeField()),
                ('is_released', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_funds', to='marketplace.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_funds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-held_at'],
            },
        ),
    ]
