# Generated by Django 5.2.4 on 2025-08-03 00:04

from django.db import migrations


def cleanup_pending_payment_orders(apps, schema_editor):
    """
    Remove all PENDING_PAYMENT orders since we no longer create them.
    These orders were created but never had successful payment.
    """
    Order = apps.get_model('marketplace', 'Order')
    
    # Delete all PENDING_PAYMENT orders
    pending_orders = Order.objects.filter(status='PENDING_PAYMENT')
    count = pending_orders.count()
    pending_orders.delete()
    
    print(f"Deleted {count} PENDING_PAYMENT orders")


def reverse_cleanup(apps, schema_editor):
    """
    This migration is irreversible since we're deleting data
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_change_default_order_status'),
    ]

    operations = [
        migrations.RunPython(cleanup_pending_payment_orders, reverse_cleanup),
    ]
