# Generated by Django 5.2.4 on 2025-08-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_cleanup_pending_payment_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_auto_reply',
            field=models.BooleanField(default=False),
        ),
    ]
