# Generated by Django 5.2.4 on 2025-08-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_add_is_auto_reply_to_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_title',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='iban',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_method',
            field=models.CharField(choices=[('easypaisa', 'EasyPaisa'), ('jazzcash', 'JazzCash'), ('bank_transfer', 'Bank Transfer')], default='jazzcash', max_length=20),
        ),
    ]
