# Generated by Django 5.2.4 on 2025-08-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0030_withdrawalrequest_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(db_index=True, help_text='Unique order identifier', max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='ProcessedPaymentCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(db_index=True, max_length=255, unique=True)),
                ('response_code', models.CharField(max_length=10)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['transaction_ref', 'processed_at'], name='marketplace_transac_409f69_idx')],
            },
        ),
    ]
