# Generated by Django 5.2.4 on 2025-08-09 02:56

import marketplace.simple_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0032_update_image_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=marketplace.simple_storage.GoogleCloudChatStorage(), upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=marketplace.simple_storage.GoogleCloudProductStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=marketplace.simple_storage.GoogleCloudProfileStorage(), upload_to='profile_pics'),
        ),
    ]
