# Generated by Django 5.2.5 on 2025-10-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0033_alter_message_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer')], default='bank_transfer', max_length=20),
        ),
    ]
