# Generated by Django 5.2.5 on 2025-10-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0035_depositrequest_transaction_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash'), ('sadapay', 'SadaPay'), ('nayapay', 'NayaPay')], default='bank_transfer', max_length=20),
        ),
    ]
