# Generated by Django 5.2.5 on 2025-10-14 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0036_withdrawalrequest_bank_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='approved_sellers',
            field=models.ManyToManyField(blank=True, help_text='Sellers allowed to create listings when special approval is required.', related_name='approved_game_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='requires_special_approval',
            field=models.BooleanField(default=False, help_text='Only approved sellers can create listings when enabled.'),
        ),
    ]
