# Generated by Django 5.2.5 on 2025-10-14 15:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0037_gamecategory_approved_sellers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
